/*******************************************************************************/
/*  SAS Program: 95_load_mock_scale.sas                                       */
/*  Purpose: Load the ~20,000-row synthetic scale fixture into                 */
/*           work.home_equity so 02_data_cleaning.sas,                         */
/*           03_aggregation_reporting.sas and 04_risk_segmentation.sas can be  */
/*           re-run over it, producing a large-scale golden set.               */
/*                                                                             */
/*  data/home_equity_scale.csv is generated by tools/generate_mock_scale.py   */
/*  (deterministic, seed 20260827). It stresses what the production extract   */
/*  cannot: every JOB/REASON level plus missings, all 9 census divisions,     */
/*  higher per-column missingness, dense clusters on every cleaning filter    */
/*  and risk threshold, and PROPCASE delimiter cases in CITY.                 */
/*                                                                             */
/*  Run this AFTER any earlier pass has exported its CSVs: it overwrites      */
/*  work.home_equity, and 02/03/04 then overwrite the downstream datasets.    */
/*******************************************************************************/

%let scalefile = /data/home_equity_scale.csv;

proc import datafile="&scalefile."
    dbms=csv
    out=work.home_equity
    replace;
    guessingrows=max;
run;

title "Scale fixture as imported (first 20 rows)";
proc print data=work.home_equity(obs=20);
    var BAD LOAN MORTDUE VALUE DEBTINC DELINQ DEROG JOB REASON CITY;
run;
title;

title "Scale fixture: import row count";
proc sql;
    select count(*) as N_IMPORTED from work.home_equity;
quit;
title;
